# Generated by Django 5.2.17 on 2026-09-06 22:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=120, unique=True)),
                ("value", models.JSONField(default=dict)),
                ("description", models.TextField(blank=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settings_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=240)),
                ("sha256", models.CharField(max_length=64)),
                ("sheet_name", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dry_run", "Simulación"),
                            ("imported", "Importado"),
                            ("review", "Requiere revisión"),
                            ("failed", "Fallido"),
                        ],
                        max_length=16,
                    ),
                ),
                ("summary", models.JSONField(default=dict)),
                (
                    "imported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_type", models.CharField(db_index=True, max_length=30)),
                ("legacy_period_label", models.CharField(blank=True, max_length=120)),
                ("concept", models.CharField(blank=True, max_length=240)),
                ("amount", models.BigIntegerField(blank=True, null=True)),
                ("original_value", models.JSONField(default=dict)),
                ("source_sheet", models.CharField(max_length=120)),
                ("source_row", models.PositiveIntegerField()),
                ("source_cell", models.CharField(max_length=20)),
                ("mapped_entity_type", models.CharField(blank=True, max_length=100)),
                ("mapped_entity_id", models.CharField(blank=True, max_length=80)),
                ("requires_review", models.BooleanField(default=False)),
                ("review_reason", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="reporting.importbatch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReconciliationIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("severity", models.CharField(default="warning", max_length=16)),
                ("legacy_value", models.BigIntegerField(blank=True, null=True)),
                ("recalculated_value", models.BigIntegerField(blank=True, null=True)),
                ("difference", models.BigIntegerField(blank=True, null=True)),
                ("message", models.TextField()),
                ("source_reference", models.CharField(max_length=120)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="reporting.importbatch",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_issues_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(fields=("sha256", "status"), name="unique_import_file_status"),
        ),
    ]
