# Generated by Django 5.2.17 on 2026-09-06 22:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Abierto"), ("closed", "Cerrado"), ("reopened", "Reabierto")],
                        default="open",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "ordering": ("-year", "-month"),
                "constraints": [
                    models.UniqueConstraint(fields=("year", "month"), name="unique_financial_period")
                ],
            },
        ),
        migrations.CreateModel(
            name="MonthlyClose",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("snapshot", models.JSONField(default=dict)),
                ("checklist", models.JSONField(default=dict)),
                ("confirmed_at", models.DateTimeField()),
                ("superseded", models.BooleanField(default=False)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_closes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="close_versions",
                        to="periods.financialperiod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeriodReopening",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField()),
                ("reopened_at", models.DateTimeField()),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reopenings",
                        to="periods.financialperiod",
                    ),
                ),
                (
                    "previous_close",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reopening_events",
                        to="periods.monthlyclose",
                    ),
                ),
                (
                    "reopened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="period_reopenings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="monthlyclose",
            constraint=models.UniqueConstraint(
                fields=("period", "version"), name="unique_monthly_close_version"
            ),
        ),
    ]
