# Generated by Django 5.2.17 on 2026-09-06 22:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("body", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Información"),
                            ("warning", "Advertencia"),
                            ("critical", "Crítica"),
                            ("success", "Éxito"),
                        ],
                        default="info",
                        max_length=12,
                    ),
                ),
                ("event_key", models.CharField(max_length=180)),
                ("action_url", models.CharField(blank=True, max_length=300)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("provider", models.CharField(default="in_app", max_length=30)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recipient", "event_key"), name="unique_notification_event_per_user"
                    )
                ],
            },
        ),
    ]
