"use client";

import { ArrowLeftIcon, CheckIcon, CoinsIcon, PlusIcon, WarningIcon } from "@phosphor-icons/react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import Link from "next/link";
import { useMemo, useState } from "react";
import { apiFetch, formatCOP, formatDate, Paginated } from "@/lib/api";
import { Button, DataTable, Input, Modal, Panel, Progress, Skeleton, StatusBadge } from "./ui";

type Row = Record<string, unknown>;
const list = <T extends Row>(endpoint: string) => {
  const [resource, query] = endpoint.split("?", 2);
  return apiFetch<Paginated<T>>(`/api/v1/${resource}/?${query ? `${query}&` : ""}page_size=100`);
};

export function DetailPage({ slug, id }: { slug: string; id: string }) {
  if (slug === "clients") return <ClientDetail id={id}/>;
  if (slug === "contracts") return <ContractDetail id={id}/>;
  if (slug === "provisions") return <ProvisionDetail id={id}/>;
  if (slug === "expenses") return <ExpenseDetail id={id}/>;
  if (slug === "monthly-close") return <MonthlyCloseWizard id={id}/>;
  return <GenericDetail slug={slug} id={id}/>;
}

function Back({ href, children }: { href: string; children: React.ReactNode }) { return <Link className="back-link" href={href}><ArrowLeftIcon size={14}/>{children}</Link>; }
function MoneyMetric({ label, value, note }: { label: string; value: number; note?: string }) { return <div className="metric-card compact"><div className="metric-head"><span>{label}</span><CoinsIcon size={15}/></div><div className="metric-value">{formatCOP(value)}</div><div className="metric-note">{note ?? "Trazable al registro fuente"}</div></div>; }
function CountMetric({ label, value }: { label: string; value: number }) { return <div className="metric-card compact"><div className="metric-head"><span>{label}</span></div><div className="metric-value">{value}</div><div className="metric-note">Registros vinculados</div></div>; }
function SimpleRows({ rows, empty="Sin registros" }: { rows: Row[]; empty?: string }) { return <DataTable rows={rows} emptyTitle={empty} columns={[{key:"name",label:"Registro",render:r=>String(r.name??r.concept??r.title??r.reference??r.id)},{key:"amount",label:"Valor",render:r=>r.amount===undefined?"—":formatCOP(Number(r.amount))},{key:"status",label:"Estado",render:r=><StatusBadge status={String(r.status??"info")}/>},{key:"created_at",label:"Fecha",render:r=>formatDate(String(r.created_at??r.received_at??r.incurred_at??""))}]}/>; }

function ClientDetail({ id }: { id: string }) {
  const [tab, setTab] = useState("Resumen");
  const client = useQuery({queryKey:["client",id],queryFn:()=>apiFetch<Row>(`/api/v1/clients/${id}/`)});
  const related = useQuery({queryKey:["client-related",id],queryFn:async()=>{
    const [projects,contracts,payments,expenses,provisions,documents,notes,activity,profitability] = await Promise.all([
      list<Row>(`projects?client=${id}`),list<Row>(`contracts?client=${id}`),list<Row>(`payments?client=${id}`),list<Row>(`expenses?client=${id}`),list<Row>(`provisions?client=${id}`),list<Row>(`documents?client=${id}`),list<Row>(`notes?client=${id}`),list<Row>(`activity?client=${id}`),apiFetch<Row[]>("/api/v1/reports/profitability/")
    ]); return {projects,contracts,payments,expenses,provisions,documents,notes,activity,profitability};
  }});
  if (client.isLoading || related.isLoading) return <Skeleton height={420}/>;
  if (!client.data) return <Panel title="Cliente no disponible"><p>No encontramos este cliente.</p></Panel>;
  const data=related.data; const profit=data?.profitability.find(x=>String(x.id)===id);
  const tabs:Record<string,Row[]>={Proyectos:data?.projects.results??[],Contratos:data?.contracts.results??[],Pagos:data?.payments.results??[],Costos:data?.expenses.results??[],Reservas:data?.provisions.results??[],Documentos:data?.documents.results??[],Notas:data?.notes.results??[],Actividad:data?.activity.results??[]};
  return <div className="page"><Back href="/clients">Clientes</Back><div className="detail-hero"><div><div className="eyebrow">EXPEDIENTE DEL CLIENTE</div><h1>{String(client.data.name)}</h1><p className="page-subtitle">{String(client.data.legal_name||client.data.contact_name||"Relación comercial activa")}</p></div><StatusBadge status={String(client.data.status)}/></div><div className="grid metrics-grid"><MoneyMetric label="Ingreso contratado" value={Number(profit?.contracted??0)}/><MoneyMetric label="Ingreso recibido" value={Number(profit?.received??0)}/><MoneyMetric label="Costos atribuidos" value={Number(profit?.directCosts??0)+Number(profit?.sharedCosts??0)}/><MoneyMetric label="Resultado económico" value={Number(profit?.economicResult??0)} note={`Margen ${profit?.marginPercentage??0}%`}/></div><div className="tabs" role="tablist">{["Resumen",...Object.keys(tabs)].map(item=><button role="tab" aria-selected={tab===item} className={tab===item?"active":""} key={item} onClick={()=>setTab(item)}>{item}</button>)}</div>{tab==="Resumen"?<div className="grid dashboard-grid"><Panel title="Estado comercial"><div className="detail-list"><span>Prefijo de cobro<strong>{String(client.data.billing_prefix)}</strong></span><span>Contacto<strong>{String(client.data.contact_name||"—")}</strong></span><span>Correo<strong>{String(client.data.contact_email||"—")}</strong></span><span>Proyectos<strong>{data?.projects.count??0}</strong></span><span>Contratos<strong>{data?.contracts.count??0}</strong></span></div></Panel><Panel title="Caja vs. rentabilidad"><p className="page-subtitle">Las reservas comprometen efectivo, pero no se contabilizan como gasto hasta su consumo.</p><div className="breakdown-total"><span>Caja después de reservas</span><strong>{formatCOP(Number(profit?.cashAfterReservations??0))}</strong></div><Progress value={Math.max(0,Number(profit?.marginPercentage??0))}/></Panel></div>:<Panel title={tab} meta={`${tabs[tab].length} registros`}><SimpleRows rows={tabs[tab]}/></Panel>}</div>;
}

function ContractDetail({ id }: { id: string }) {
  const qc=useQueryClient();
  const contract=useQuery({queryKey:["contract",id],queryFn:()=>apiFetch<Row>(`/api/v1/contracts/${id}/`)});
  const versions=useQuery({queryKey:["contract-versions",id],queryFn:()=>list<Row>(`contract-versions?contract=${id}`)});
  const charges=useQuery({queryKey:["contract-charges",id],queryFn:()=>list<Row>(`scheduled-charges?contract=${id}`)});
  const generate=useMutation({mutationFn:()=>apiFetch(`/api/v1/contracts/${id}/generate_schedule/`,{method:"POST",body:"{}"}),onSuccess:()=>qc.invalidateQueries({queryKey:["contract-charges",id]})});
  if(contract.isLoading)return <Skeleton height={430}/>; const c=contract.data;
  if(!c)return <Panel title="Contrato no disponible"><p>No encontramos este contrato.</p></Panel>;
  const billed=(charges.data?.results??[]).reduce((sum,row)=>sum+Number(row.amount??0),0);
  const start=new Date(String(c.start_date)); const end=c.end_date?new Date(String(c.end_date)):null; const now=new Date(); const duration=end?Math.max(1,(end.getFullYear()-start.getFullYear())*12+end.getMonth()-start.getMonth()+1):0; const elapsed=Math.max(1,(now.getFullYear()-start.getFullYear())*12+now.getMonth()-start.getMonth()+1);
  return <div className="page"><Back href="/contracts">Contratos</Back><div className="detail-hero"><div><div className="eyebrow">CONTROL CONTRACTUAL</div><h1>{String(c.name)}</h1><p className="page-subtitle">{end?`Mes ${Math.min(elapsed,duration)} de ${duration} · Finaliza ${formatDate(String(c.end_date))}`:"Sin fecha final"}</p></div><div className="hero-actions"><StatusBadge status={String(c.status)}/><Button onClick={()=>generate.mutate()} disabled={generate.isPending}><PlusIcon size={15}/>Generar calendario</Button></div></div><div className="grid metrics-grid"><MoneyMetric label="Valor programado" value={billed}/><CountMetric label="Obligaciones" value={charges.data?.count??0}/><MoneyMetric label="Restante contractual" value={Math.max(0,Number(versions.data?.results[0]?.total_value??billed)-billed)}/><div className="metric-card compact"><div className="metric-head"><span>Avance temporal</span></div><div className="metric-value">{duration?Math.round(Math.min(elapsed,duration)/duration*100):0}%</div><Progress value={duration?Math.min(elapsed,duration)/duration*100:0}/></div></div><div className="grid dashboard-grid"><Panel title="Versiones" meta="Histórico inmutable"><SimpleRows rows={versions.data?.results??[]} empty="No hay versiones"/></Panel><Panel title="Calendario generado" meta={`${charges.data?.count??0} obligaciones`}><SimpleRows rows={charges.data?.results??[]} empty="Genera el calendario contractual"/></Panel></div></div>;
}

function ProvisionDetail({ id }: { id: string }) {
  const [open,setOpen]=useState(false); const [amount,setAmount]=useState(""); const qc=useQueryClient();
  const plan=useQuery({queryKey:["provision",id],queryFn:()=>apiFetch<Row>(`/api/v1/provisions/${id}/`)});
  const contribution=useMutation({mutationFn:()=>apiFetch(`/api/v1/provisions/${id}/contribute/`,{method:"POST",body:JSON.stringify({amount:Number(amount)})}),onSuccess:()=>{setOpen(false);setAmount("");qc.invalidateQueries({queryKey:["provision",id]});}});
  if(plan.isLoading)return <Skeleton height={420}/>; const p=plan.data; if(!p)return <Panel title="Provisión no disponible"><p>No encontramos esta provisión.</p></Panel>;
  return <div className="page"><Back href="/provisions">Provisiones</Back><div className="detail-hero"><div><div className="eyebrow">RESERVA PARA OBLIGACIÓN</div><h1>{String(p.name)}</h1><p className="page-subtitle">Vence {formatDate(String(p.due_date))}</p></div><Button onClick={()=>setOpen(true)}><PlusIcon size={15}/>Registrar aporte</Button></div><div className="grid metrics-grid"><MoneyMetric label="Objetivo" value={Number(p.target_amount)}/><MoneyMetric label="Reservado" value={Number(p.reserved_balance)}/><MoneyMetric label="Faltante" value={Number(p.remaining_amount)}/><MoneyMetric label="Aporte sugerido" value={Number(p.suggested_contribution)}/></div><Panel title="Progreso de la reserva" meta={`${p.progress_percentage}%`}><Progress value={Number(p.progress_percentage)}/><div className="detail-list" style={{marginTop:18}}><span>Inicio de aportes<strong>{formatDate(String(p.contribution_start_date))}</strong></span><span>Incremento estimado<strong>{String(p.estimated_increase_basis_points??0)} pb</strong></span><span>Propietario financiero<strong>{String(p.owner_type)}</strong></span><span>Estado<strong><StatusBadge status={String(p.status)}/></strong></span></div></Panel><Modal open={open} onClose={()=>setOpen(false)} title="Registrar aporte" description={`Sugerido hoy: ${formatCOP(Number(p.suggested_contribution))}`}><form className="auth-fields" onSubmit={e=>{e.preventDefault();contribution.mutate()}}><Input label="Monto COP" type="number" required value={amount} onChange={e=>setAmount(e.target.value)}/><Button disabled={contribution.isPending} type="submit">Confirmar aporte</Button></form></Modal></div>;
}

function ExpenseDetail({ id }: { id: string }) { const expense=useQuery({queryKey:["expense",id],queryFn:()=>apiFetch<Row>(`/api/v1/expenses/${id}/`)}); const allocations=useQuery({queryKey:["expense-allocations",id],queryFn:()=>list<Row>(`expense-allocations?expense=${id}`)}); if(expense.isLoading)return <Skeleton height={350}/>; const e=expense.data;if(!e)return <Panel title="Gasto no disponible"><p>No encontramos este gasto.</p></Panel>;return <div className="page"><Back href="/expenses">Gastos</Back><div className="detail-hero"><div><div className="eyebrow">TRAZABILIDAD DEL COSTO</div><h1>{String(e.concept)}</h1><p className="page-subtitle">Registrado {formatDate(String(e.incurred_at))}</p></div><StatusBadge status={e.is_void?"void":e.paid_at?"paid":"pending"}/></div><div className="grid metrics-grid"><MoneyMetric label="Valor" value={Number(e.amount)}/><MoneyMetric label="Asignado" value={(allocations.data?.results??[]).reduce((s,r)=>s+Number(r.amount??0),0)}/></div><Panel title="Snapshot de asignación" meta={e.allocation_confirmed?"Confirmado":"Pendiente"}><SimpleRows rows={allocations.data?.results??[]} empty="Este gasto todavía no tiene asignaciones confirmadas"/></Panel></div>; }

const closeSteps=["Reconciliar cuentas bancarias","Revisar ingresos esperados vs. recibidos","Revisar cartera pendiente y vencida","Revisar gastos","Revisar provisiones y fondos","Calcular dinero comprometido","Calcular dinero disponible","Aplicar política vigente","Revisar distribución","Confirmar cierre"];
function MonthlyCloseWizard({id}:{id:string}) { const qc=useQueryClient(); const [checks,setChecks]=useState<Record<string,boolean>>({}); const [reason,setReason]=useState(""); const period=useQuery({queryKey:["period",id],queryFn:()=>apiFetch<Row>(`/api/v1/periods/${id}/`)}); const close=useMutation({mutationFn:()=>apiFetch(`/api/v1/periods/${id}/close/`,{method:"POST",body:JSON.stringify({checklist:checks})}),onSuccess:()=>qc.invalidateQueries({queryKey:["period",id]})}); const reopen=useMutation({mutationFn:()=>apiFetch(`/api/v1/periods/${id}/reopen/`,{method:"POST",body:JSON.stringify({reason})}),onSuccess:()=>qc.invalidateQueries({queryKey:["period",id]})}); const done=Object.values(checks).filter(Boolean).length; if(period.isLoading)return <Skeleton height={500}/>; const p=period.data;if(!p)return <Panel title="Periodo no disponible"><p>No encontramos este periodo.</p></Panel>; return <div className="page"><Back href="/monthly-close">Cierres</Back><div className="detail-hero"><div><div className="eyebrow">CIERRE DE MES</div><h1>{String(p.month).padStart(2,"0")}/{String(p.year)}</h1><p className="page-subtitle">Snapshot auditable · {done} de 10 controles revisados</p></div><StatusBadge status={String(p.status)}/></div><div className="close-layout"><Panel title="Lista de control" meta={`${done*10}%`}><Progress value={done*10}/><div className="checklist">{closeSteps.map((label,index)=><label key={label}><input type="checkbox" checked={!!checks[String(index+1)]} onChange={event=>setChecks({...checks,[String(index+1)]:event.target.checked})}/><span className="checkmark"><CheckIcon size={13}/></span><span><small>Paso {index+1}</small>{label}</span></label>)}</div></Panel><Panel title="Confirmación financiera"><div className="impact-box"><WarningIcon size={19}/><p>El cierre conserva una fotografía completa. Reabrir no la elimina: crea una nueva versión y exige motivo.</p></div>{p.status==="closed"?<div className="auth-fields"><Input label="Motivo para reabrir" value={reason} onChange={e=>setReason(e.target.value)}/><Button variant="danger" disabled={!reason||reopen.isPending} onClick={()=>reopen.mutate()}>Reabrir periodo</Button></div>:<Button style={{width:"100%"}} disabled={done!==10||close.isPending} onClick={()=>close.mutate()}>Confirmar cierre</Button>}</Panel></div></div>; }

function GenericDetail({slug,id}:{slug:string;id:string}) { const item=useQuery({queryKey:[slug,id],queryFn:()=>apiFetch<Row>(`/api/v1/${slug}/${id}/`)}); const entries=useMemo(()=>Object.entries(item.data??{}).filter(([key])=>!["id","created_at","updated_at"].includes(key)),[item.data]); if(item.isLoading)return <Skeleton height={320}/>; return <div className="page"><Back href={`/${slug}`}>Volver</Back><div className="detail-hero"><div><div className="eyebrow">DETALLE AUDITABLE</div><h1>{String(item.data?.name??item.data?.concept??item.data?.title??"Registro")}</h1></div></div><Panel title="Datos del registro"><div className="detail-list">{entries.map(([key,value])=><span key={key}>{key.replaceAll("_"," ")}<strong>{typeof value==="boolean"?(value?"Sí":"No"):String(value??"—")}</strong></span>)}</div></Panel></div>; }
