"use client";

import { PlusIcon, SlidersHorizontalIcon } from "@phosphor-icons/react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { apiFetch, formatCOP, formatDate, Paginated } from "@/lib/api";
import { Button, DataTable, Input, Modal, Panel, StatusBadge } from "./ui";
import { CalendarPage, ReportsPage } from "./reporting-pages";

type RecordRow = Record<string, unknown>;
type Field = { key: string; label: string; type?: "text" | "number" | "date" | "datetime" | "select"; options?: { value: string; label: string }[]; required?: boolean; default?: string };
type Config = { title: string; eyebrow: string; description: string; endpoint: string; singular: string; fields?: Field[]; columns: { key: string; label: string; kind?: "money" | "date" | "status" }[] };

const configs: Record<string, Config> = {
  clients: { title: "Clientes", eyebrow: "RELACIONES COMERCIALES", description: "Expediente financiero, contractual y operativo de cada cliente.", endpoint: "clients", singular: "cliente", fields: [{key:"name",label:"Nombre",required:true},{key:"billing_prefix",label:"Prefijo de cobro",required:true},{key:"contact_name",label:"Contacto"},{key:"contact_email",label:"Correo"},{key:"status",label:"Estado",type:"select",default:"active",options:[{value:"active",label:"Activo"},{value:"lead",label:"Prospecto"}]}], columns:[{key:"name",label:"Cliente"},{key:"billing_prefix",label:"Prefijo"},{key:"contact_name",label:"Contacto"},{key:"status",label:"Estado",kind:"status"},{key:"created_at",label:"Creado",kind:"date"}] },
  projects: { title: "Proyectos", eyebrow: "ENTREGA Y SERVICIO", description: "Separa el trabajo realizado de los contratos que lo regulan.", endpoint:"projects",singular:"proyecto",fields:[{key:"client",label:"ID del cliente",required:true},{key:"name",label:"Nombre",required:true},{key:"description",label:"Descripción"},{key:"status",label:"Estado",type:"select",default:"active",options:[{value:"active",label:"Activo"},{value:"planned",label:"Planeado"},{value:"paused",label:"Pausado"}]}],columns:[{key:"name",label:"Proyecto"},{key:"client",label:"Cliente"},{key:"status",label:"Estado",kind:"status"},{key:"start_date",label:"Inicio",kind:"date"},{key:"end_date",label:"Final",kind:"date"}]},
  contracts: {title:"Contratos",eyebrow:"CONTROL CONTRACTUAL",description:"Vigencias, versiones, servicios y calendario de cobro sin modificar el pasado.",endpoint:"contracts",singular:"contrato",fields:[{key:"client",label:"ID del cliente",required:true},{key:"name",label:"Nombre",required:true},{key:"start_date",label:"Fecha inicial",type:"date",required:true},{key:"end_date",label:"Fecha final",type:"date"},{key:"status",label:"Estado",type:"select",default:"draft",options:[{value:"draft",label:"Borrador"},{value:"active",label:"Activo"}]}],columns:[{key:"name",label:"Contrato"},{key:"client",label:"Cliente"},{key:"start_date",label:"Inicio",kind:"date"},{key:"end_date",label:"Final",kind:"date"},{key:"status",label:"Estado",kind:"status"}]},
  billing:{title:"Cobros",eyebrow:"CUENTAS Y CUOTAS",description:"Obligaciones, cuentas de cobro, pagos parciales y condonaciones.",endpoint:"installments",singular:"cuota",columns:[{key:"due_date",label:"Vencimiento",kind:"date"},{key:"amount",label:"Valor",kind:"money"},{key:"paid_amount",label:"Pagado",kind:"money"},{key:"balance",label:"Saldo",kind:"money"},{key:"status",label:"Estado",kind:"status"}]},
  payments:{title:"Pagos recibidos",eyebrow:"DINERO REAL",description:"Cada ingreso bancario permanece separado de los periodos a los que se asigna.",endpoint:"payments",singular:"pago",fields:[{key:"client",label:"ID del cliente",required:true},{key:"bank_account",label:"ID de la cuenta",required:true},{key:"amount",label:"Valor",type:"number",required:true},{key:"received_at",label:"Fecha y hora",type:"datetime",required:true},{key:"reference",label:"Referencia"}],columns:[{key:"client",label:"Cliente"},{key:"amount",label:"Valor",kind:"money"},{key:"received_at",label:"Recibido",kind:"date"},{key:"reference",label:"Referencia"},{key:"is_void",label:"Anulado"}]},
  expenses:{title:"Gastos",eyebrow:"COSTOS CONTROLADOS",description:"Costos directos, globales o compartidos con snapshots de asignación.",endpoint:"expenses",singular:"gasto",fields:[{key:"category",label:"ID de categoría",required:true},{key:"scope",label:"Alcance",type:"select",default:"global",options:[{value:"global",label:"Global"},{value:"client",label:"Cliente"},{value:"shared",label:"Compartido"}]},{key:"client",label:"ID cliente (opcional)"},{key:"concept",label:"Concepto",required:true},{key:"amount",label:"Valor",type:"number",required:true},{key:"incurred_at",label:"Fecha y hora",type:"datetime",required:true}],columns:[{key:"concept",label:"Concepto"},{key:"scope",label:"Alcance"},{key:"client",label:"Cliente"},{key:"amount",label:"Valor",kind:"money"},{key:"incurred_at",label:"Fecha",kind:"date"}]},
  provisions:{title:"Provisiones",eyebrow:"OBLIGACIONES FUTURAS",description:"Ahorra de forma gradual y recalcula el faltante sin perder historial.",endpoint:"provisions",singular:"provisión",fields:[{key:"name",label:"Nombre",required:true},{key:"owner_type",label:"Propietario",type:"select",default:"global",options:[{value:"global",label:"Global"},{value:"client",label:"Cliente"}]},{key:"client",label:"ID cliente (opcional)"},{key:"category",label:"ID de categoría",required:true},{key:"target_amount",label:"Objetivo",type:"number",required:true},{key:"due_date",label:"Vencimiento",type:"date",required:true},{key:"contribution_start_date",label:"Inicio de aportes",type:"date",required:true}],columns:[{key:"name",label:"Obligación"},{key:"target_amount",label:"Objetivo",kind:"money"},{key:"reserved_balance",label:"Reservado",kind:"money"},{key:"remaining_amount",label:"Faltante",kind:"money"},{key:"due_date",label:"Vence",kind:"date"},{key:"status",label:"Estado",kind:"status"}]},
  funds:{title:"Fondos internos",eyebrow:"ASIGNACIÓN DE EFECTIVO",description:"Reservas operativas independientes que no se confunden con gastos.",endpoint:"funds",singular:"fondo",fields:[{key:"name",label:"Nombre",required:true},{key:"description",label:"Descripción"}],columns:[{key:"name",label:"Fondo"},{key:"description",label:"Propósito"},{key:"active",label:"Activo"},{key:"created_at",label:"Creado",kind:"date"}]},
  treasury:{title:"Tesorería",eyebrow:"CUENTAS PROPIAS",description:"Saldos bancarios y trazabilidad manual de movimientos.",endpoint:"bank-accounts",singular:"cuenta",fields:[{key:"name",label:"Nombre",required:true},{key:"bank",label:"Banco"},{key:"account_type",label:"Tipo"},{key:"last_digits",label:"Últimos 4 dígitos"},{key:"opening_balance",label:"Saldo inicial",type:"number",required:true}],columns:[{key:"name",label:"Cuenta"},{key:"bank",label:"Banco"},{key:"account_type",label:"Tipo"},{key:"last_digits",label:"Terminación"},{key:"opening_balance",label:"Saldo inicial",kind:"money"},{key:"active",label:"Activa"}]},
  transfers:{title:"Transferencias",eyebrow:"MOVIMIENTOS INTERNOS",description:"Salida y entrada balanceadas; impacto financiero neto igual a cero.",endpoint:"transfers",singular:"transferencia",fields:[{key:"from_account",label:"ID cuenta origen",required:true},{key:"to_account",label:"ID cuenta destino",required:true},{key:"amount",label:"Valor",type:"number",required:true},{key:"occurred_at",label:"Fecha y hora",type:"datetime",required:true},{key:"reason",label:"Motivo",required:true}],columns:[{key:"from_account",label:"Origen"},{key:"to_account",label:"Destino"},{key:"amount",label:"Valor",kind:"money"},{key:"occurred_at",label:"Fecha",kind:"date"},{key:"reason",label:"Motivo"}]},
  distributions:{title:"Distribuciones",eyebrow:"SOCIOS Y GLOBAL",description:"Aplicación versionada de la política vigente sobre dinero realmente distribuible.",endpoint:"distribution-runs",singular:"distribución",columns:[{key:"period",label:"Periodo"},{key:"distributable_base",label:"Base",kind:"money"},{key:"policy",label:"Política"},{key:"status",label:"Estado",kind:"status"},{key:"created_at",label:"Calculada",kind:"date"}]},
  "monthly-close":{title:"Cierre mensual",eyebrow:"WIZARD DE CONTROL",description:"Diez pasos para conciliar, revisar y congelar una fotografía auditable del mes.",endpoint:"periods",singular:"periodo",fields:[{key:"year",label:"Año",type:"number",required:true},{key:"month",label:"Mes",type:"number",required:true}],columns:[{key:"year",label:"Año"},{key:"month",label:"Mes"},{key:"status",label:"Estado",kind:"status"},{key:"updated_at",label:"Actualizado",kind:"date"}]},
  documents:{title:"Documentos",eyebrow:"EXPEDIENTE DIGITAL",description:"Contratos, cuentas, comprobantes y anexos con versiones preservadas.",endpoint:"documents",singular:"documento",fields:[{key:"name",label:"Nombre",required:true},{key:"document_type",label:"Tipo",type:"select",default:"other",options:[{value:"contract",label:"Contrato"},{value:"quote",label:"Cotización"},{value:"charge",label:"Cuenta de cobro"},{value:"other",label:"Otro"}]},{key:"client",label:"ID del cliente"},{key:"document_date",label:"Fecha",type:"date"}],columns:[{key:"name",label:"Documento"},{key:"document_type",label:"Tipo"},{key:"client",label:"Cliente"},{key:"document_date",label:"Fecha",kind:"date"},{key:"archived",label:"Archivado"}]},
  notifications:{title:"Notificaciones",eyebrow:"ALERTAS INTERNAS",description:"Cobros, contratos, provisiones y obligaciones que requieren atención.",endpoint:"notifications",singular:"notificación",columns:[{key:"title",label:"Alerta"},{key:"severity",label:"Prioridad",kind:"status"},{key:"created_at",label:"Fecha",kind:"date"},{key:"read_at",label:"Leída",kind:"date"}]},
  audit:{title:"Auditoría",eyebrow:"TRAZABILIDAD",description:"Quién cambió qué, cuándo y desde dónde, con valores anteriores y posteriores.",endpoint:"audit",singular:"evento",columns:[{key:"created_at",label:"Fecha",kind:"date"},{key:"action",label:"Acción"},{key:"entity_type",label:"Entidad"},{key:"entity_id",label:"ID"},{key:"ip_address",label:"IP"}]}
};

export function ModulePage({ slug }: { slug: string }) {
  const config = configs[slug] ?? {title: titleCase(slug),eyebrow:"GLOBAL BILLING",description:"Módulo operativo del sistema.",endpoint:slug,singular:"registro",columns:[{key:"id",label:"ID"},{key:"created_at",label:"Creado",kind:"date"}]};
  const queryClient = useQueryClient();
  const [createOpen, setCreateOpen] = useState(false);
  const [form, setForm] = useState<Record<string,string>>(() => Object.fromEntries((config.fields ?? []).map(f => [f.key,f.default ?? ""])));
  const list = useQuery({queryKey:["module",config.endpoint],queryFn:()=>apiFetch<Paginated<RecordRow>>(`/api/v1/${config.endpoint}/?page_size=50`)});
  const create = useMutation({mutationFn:()=>apiFetch(`/api/v1/${config.endpoint}/`,{method:"POST",body:JSON.stringify(Object.fromEntries(Object.entries(form).filter(([,v])=>v!=="").map(([k,v])=>[(config.fields?.find(f=>f.key===k)?.type)==="number" ? k : k,(config.fields?.find(f=>f.key===k)?.type)==="number" ? Number(v) : v])))}),onSuccess:()=>{queryClient.invalidateQueries({queryKey:["module",config.endpoint]});setCreateOpen(false);}});
  const columns = useMemo(() => config.columns.map(column => ({key:column.key,label:column.label,render:(row:RecordRow)=> column.kind === "money" ? formatCOP(Number(row[column.key] ?? 0)) : column.kind === "date" ? formatDate(row[column.key] as string | null) : column.kind === "status" ? <StatusBadge status={String(row[column.key] ?? "info")}/> : String(row[column.key] ?? "—")})),[config.columns]);
  const isCalendar = slug === "calendar";
  const isReports = slug === "reports";
  const isSettings = slug === "settings";

  if (isCalendar) return <CalendarPage/>;
  if (isReports) return <ReportsPage/>;
  if (isSettings) return <SettingsPage/>;
  return <div className="page"><div className="page-header"><div><div className="eyebrow">{config.eyebrow}</div><h1>{config.title}</h1><p className="page-subtitle">{config.description}</p></div>{config.fields?.length ? <Button onClick={()=>setCreateOpen(true)}><PlusIcon size={15}/>Crear {config.singular}</Button> : <Button variant="secondary"><SlidersHorizontalIcon size={15}/>Filtros</Button>}</div><Panel title={`Listado de ${config.title.toLowerCase()}`} meta={list.data ? `${list.data.count} registros` : "Cargando"}>{list.isLoading ? <div style={{padding:30}}>Cargando registros…</div> : list.isError ? <div className="empty"><p>{(list.error as Error).message}</p></div> : <DataTable columns={columns} rows={list.data?.results ?? []} emptyTitle={`No hay ${config.title.toLowerCase()} todavía`}/>}</Panel><Modal open={createOpen} onClose={()=>setCreateOpen(false)} title={`Crear ${config.singular}`} description="Los campos obligatorios están marcados."><form className="auth-fields" onSubmit={e=>{e.preventDefault();create.mutate();}}>{config.fields?.map(field => field.type === "select" ? <div className="field" key={field.key}><label htmlFor={field.key}>{field.label}{field.required ? " *" : ""}</label><select id={field.key} className="input" value={form[field.key] ?? ""} onChange={e=>setForm({...form,[field.key]:e.target.value})}>{field.options?.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select></div> : <Input key={field.key} id={field.key} label={`${field.label}${field.required ? " *" : ""}`} required={field.required} type={field.type === "datetime" ? "datetime-local" : field.type ?? "text"} value={form[field.key] ?? ""} onChange={e=>setForm({...form,[field.key]:e.target.value})}/>)}{create.isError && <div className="field-error">{(create.error as Error).message}</div>}<Button type="submit" disabled={create.isPending}>{create.isPending ? "Guardando…" : `Crear ${config.singular}`}</Button></form></Modal></div>;
}

function SettingsPage(){const cards=["General y marca","Usuarios y seguridad","Emisores","Cuentas bancarias","Categorías de gasto","Fondos internos","Política de distribución","Notificaciones","Documentos","Backups y sistema"];return <div className="page"><div className="page-header"><div><div className="eyebrow">SISTEMA</div><h1>Configuración</h1><p className="page-subtitle">Parámetros centralizados de Global Billing.</p></div></div><div className="grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))"}}>{cards.map(card=><Panel title={card} key={card}><p className="page-subtitle">Administra este grupo desde una superficie auditable y preparada para crecer.</p><Button variant="secondary" style={{marginTop:13}}>Abrir configuración</Button></Panel>)}</div></div>}
function titleCase(value:string){return value.split("-").map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(" ")}
