"use client";

import { CalendarBlankIcon, DownloadSimpleIcon, TrendUpIcon } from "@phosphor-icons/react";
import { useQuery } from "@tanstack/react-query";
import Link from "next/link";
import { apiFetch, formatCOP, formatDate } from "@/lib/api";
import { Badge, Button, DataTable, Panel, Skeleton } from "./ui";

type CalendarEvent = { id:string;type:string;date:string;title:string;amount:number|null;status:string;href:string };
type Projection = {days:number;realAvailable:number;expectedIncome:number;futureExpenses:number;suggestedProvisions:number;projectedAvailable:number;contractsExpiring:unknown[]};
type Profitability = {id:string;client:string;contracted:number;collectible:number;received:number;waivers:number;directCosts:number;sharedCosts:number;reserved:number;economicResult:number;marginPercentage:number;cashAfterReservations:number};
type Aging = {asOf:string;totals:Record<string,number>;rows:Record<string,unknown>[]};

export function CalendarPage(){const events=useQuery({queryKey:["calendar"],queryFn:()=>apiFetch<CalendarEvent[]>("/api/v1/calendar/events/")});return <div className="page"><div className="page-header"><div><div className="eyebrow">PRÓXIMOS 90 DÍAS</div><h1>Calendario financiero</h1><p className="page-subtitle">Cobros, vencimientos, provisiones y renovaciones en una sola agenda.</p></div><Button variant="secondary"><CalendarBlankIcon size={15}/>Hoy</Button></div><Panel title="Agenda" meta={events.data?`${events.data.length} eventos`:"Cargando"}>{events.isLoading?<Skeleton height={230}/>:events.data?.length?<div className="list">{events.data.map(event=><Link className="list-row" href={event.href} key={`${event.type}-${event.id}`}><div><div className="list-title">{event.title}</div><div className="list-subtitle"><Badge>{event.type}</Badge></div></div><div><div className="list-amount">{event.amount===null?"—":formatCOP(event.amount)}</div><div className="list-date">{formatDate(event.date)}</div></div></Link>)}</div>:<div className="empty"><CalendarBlankIcon size={28}/><p>No hay eventos en los próximos 90 días.</p></div>}</Panel></div>}

export function ReportsPage(){const projection=useQuery({queryKey:["projection",90],queryFn:()=>apiFetch<Projection>("/api/v1/reports/projection/?days=90")});const profitability=useQuery({queryKey:["profitability"],queryFn:()=>apiFetch<Profitability[]>("/api/v1/reports/profitability/")});const aging=useQuery({queryKey:["aging"],queryFn:()=>apiFetch<Aging>("/api/v1/reports/aging/")});const profitColumns=[{key:"client",label:"Cliente"},{key:"received",label:"Recibido",render:(r:Record<string,unknown>)=>formatCOP(Number(r.received))},{key:"directCosts",label:"Costos directos",render:(r:Record<string,unknown>)=>formatCOP(Number(r.directCosts))},{key:"sharedCosts",label:"Compartidos",render:(r:Record<string,unknown>)=>formatCOP(Number(r.sharedCosts))},{key:"economicResult",label:"Resultado",render:(r:Record<string,unknown>)=>formatCOP(Number(r.economicResult))},{key:"marginPercentage",label:"Margen",render:(r:Record<string,unknown>)=>`${r.marginPercentage}%`}];return <div className="page"><div className="page-header"><div><div className="eyebrow">REAL VS. PROYECTADO</div><h1>Reportes</h1><p className="page-subtitle">Cartera, rentabilidad y proyección con exportaciones listas para compartir.</p></div><div style={{display:"flex",gap:8}}><a className="button secondary" href="/api/v1/reports/monthly.pdf"><DownloadSimpleIcon size={15}/>PDF</a><a className="button primary" href="/api/v1/reports/monthly.xlsx"><DownloadSimpleIcon size={15}/>XLSX</a></div></div><div className="grid metrics-grid">{[["Disponible real",projection.data?.realAvailable],["Ingresos esperados",projection.data?.expectedIncome],["Obligaciones futuras",(projection.data?.futureExpenses??0)+(projection.data?.suggestedProvisions??0)],["Disponible proyectado",projection.data?.projectedAvailable]].map(([label,value])=><div className="metric-card" key={String(label)}><div className="metric-head"><span>{label}</span><span className="metric-icon"><TrendUpIcon size={16}/></span></div><div className="metric-value">{projection.isLoading?"—":formatCOP(Number(value??0))}</div><div className="metric-note">Horizonte 90 días</div></div>)}</div><div className="grid dashboard-grid"><Panel title="Rentabilidad por cliente" meta="Resultado económico"><DataTable columns={profitColumns} rows={(profitability.data??[]) as unknown as Record<string,unknown>[]} emptyTitle="Sin rentabilidad calculable"/></Panel><Panel title="Cartera por antigüedad" meta={aging.data?formatDate(aging.data.asOf):""}><div className="list">{Object.entries(aging.data?.totals??{}).map(([bucket,total])=><div className="list-row" key={bucket}><div className="list-title">{bucket}</div><div className="list-amount">{formatCOP(total)}</div></div>)}{aging.data&&Object.keys(aging.data.totals).length===0&&<div className="empty"><p>No hay cartera pendiente.</p></div>}</div></Panel></div></div>}
