# Generated by Django 5.2.17 on 2026-09-06 22:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingIssuer",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=180)),
                ("identification_type", models.CharField(blank=True, max_length=30)),
                ("identification", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("address", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BillingSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_sequence",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChargeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_void", models.BooleanField(default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
                ("consecutive", models.CharField(max_length=50, unique=True)),
                ("revision", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("review", "Pendiente de revisión"),
                            ("approved", "Aprobada"),
                            ("sent", "Enviada"),
                            ("cancelled", "Cancelada"),
                        ],
                        db_index=True,
                        default="review",
                        max_length=16,
                    ),
                ),
                ("concept", models.TextField()),
                ("amount", models.BigIntegerField(validators=[apps.common.models.validate_non_negative])),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("is_outdated", models.BooleanField(db_index=True, default=False)),
                ("pdf_file", models.FileField(blank=True, upload_to="charge_documents/%Y/%m/")),
                ("source_fingerprint", models.CharField(max_length=64)),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charge_documents",
                        to="billing.billingissuer",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                ("variant_key", models.CharField(max_length=40)),
                ("edited_by_user", models.BooleanField(default=False)),
                (
                    "charge_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="billing.chargedocument",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_void", models.BooleanField(default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
                ("sequence", models.PositiveSmallIntegerField()),
                ("due_date", models.DateField(db_index=True)),
                ("amount", models.BigIntegerField(validators=[apps.common.models.validate_non_negative])),
                (
                    "waived_amount",
                    models.BigIntegerField(default=0, validators=[apps.common.models.validate_non_negative]),
                ),
                (
                    "status_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("scheduled", "Programado"),
                            ("document_pending", "Cuenta pendiente"),
                            ("document_draft", "Cuenta generada"),
                            ("sent", "Enviado"),
                            ("due_soon", "Por vencer"),
                            ("overdue", "Vencido"),
                            ("partial", "Pagado parcialmente"),
                            ("paid", "Pagado"),
                            ("waived", "Condonado"),
                            ("cancelled", "Cancelado"),
                        ],
                        max_length=24,
                    ),
                ),
                ("status_override_reason", models.TextField(blank=True)),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("due_date", "sequence"),
            },
        ),
        migrations.AddField(
            model_name="chargedocument",
            name="installment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="billing.installment",
            ),
        ),
        migrations.CreateModel(
            name="ScheduledCharge",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_void", models.BooleanField(default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
                ("service_period_start", models.DateField(db_index=True)),
                ("service_period_end", models.DateField()),
                ("amount", models.BigIntegerField(validators=[apps.common.models.validate_non_negative])),
                (
                    "waived_amount",
                    models.BigIntegerField(default=0, validators=[apps.common.models.validate_non_negative]),
                ),
                (
                    "cancelled_amount",
                    models.BigIntegerField(default=0, validators=[apps.common.models.validate_non_negative]),
                ),
                ("legacy_source", models.BooleanField(default=False)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduled_charges",
                        to="contracts.contract",
                    ),
                ),
                (
                    "contract_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduled_charges",
                        to="contracts.contractversion",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("service_period_start",),
            },
        ),
        migrations.AddField(
            model_name="installment",
            name="charge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="installments",
                to="billing.scheduledcharge",
            ),
        ),
        migrations.CreateModel(
            name="Waiver",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_void", models.BooleanField(default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
                ("amount", models.BigIntegerField(validators=[apps.common.models.validate_non_negative])),
                ("reason", models.TextField()),
                ("granted_at", models.DateTimeField()),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waivers_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waivers",
                        to="billing.installment",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="chargedocument",
            constraint=models.UniqueConstraint(
                fields=("installment", "revision"), name="unique_charge_document_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="chargedocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_outdated", False), ("is_void", False)),
                fields=("installment",),
                name="one_current_charge_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledcharge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_void", False)),
                fields=("contract", "service_period_start"),
                name="unique_active_charge_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledcharge",
            constraint=models.CheckConstraint(
                condition=models.Q(("waived_amount__gte", 0)), name="charge_waived_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="installment",
            constraint=models.UniqueConstraint(
                fields=("charge", "sequence"), name="unique_installment_sequence"
            ),
        ),
    ]
