# Generated by Django 5.2.17 on 2026-09-06 22:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("legal_name", models.CharField(blank=True, max_length=220)),
                ("billing_prefix", models.CharField(max_length=24, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("inactive", "Inactivo"),
                            ("lead", "Prospecto"),
                            ("archived", "Archivado"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=180)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("legacy_source", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("name",),
                "indexes": [models.Index(fields=["status", "name"], name="clients_cli_status_44bcec_idx")],
            },
        ),
        migrations.CreateModel(
            name="ClientBillingProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("billing_name", models.CharField(max_length=220)),
                ("identification_type", models.CharField(blank=True, max_length=30)),
                ("identification", models.CharField(blank=True, max_length=80)),
                ("billing_email", models.EmailField(blank=True, max_length=254)),
                ("billing_address", models.TextField(blank=True)),
                ("payment_notes", models.TextField(blank=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_profile",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
