# Generated by Django 5.2.17 on 2026-09-06 23:09

from django.db import migrations, models

import apps.documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to=apps.documents.models.secure_document_path, validators=[apps.documents.models.validate_document_file]),
        ),
    ]
