# Generated by Django 5.2.17 on 2026-09-06 22:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("active", "Activo"),
                            ("suspended", "Suspendido"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                            ("expired", "Vencido"),
                            ("renewal_pending", "Renovación pendiente"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("billing_periodicity", models.CharField(default="monthly", max_length=24)),
                ("renewal_mode", models.CharField(default="manual", max_length=24)),
                ("conditions", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="clients.client",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "Único"),
                            ("monthly", "Mensual"),
                            ("bimonthly", "Cada 2 meses"),
                            ("quarterly", "Trimestral"),
                            ("custom", "Personalizado"),
                        ],
                        default="monthly",
                        max_length=16,
                    ),
                ),
                ("due_days", models.JSONField(default=list, help_text="Días del mes; p. ej. [11, 26].")),
                (
                    "split_percentages",
                    models.JSONField(default=list, help_text="Porcentajes enteros que suman 100."),
                ),
                ("custom_schedule", models.JSONField(blank=True, default=list)),
                ("generate_days_before", models.PositiveSmallIntegerField(default=2)),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_rule",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContractService",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_services",
                        to="contracts.contract",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_services",
                        to="projects.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.PositiveIntegerField()),
                ("effective_from", models.DateField()),
                ("effective_until", models.DateField(blank=True, null=True)),
                (
                    "period_amount",
                    models.BigIntegerField(validators=[apps.common.models.validate_non_negative]),
                ),
                ("currency", models.CharField(default="COP", editable=False, max_length=3)),
                ("change_reason", models.TextField()),
                ("conditions_snapshot", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="contracts.contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("contract", "version_number"),
            },
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["status", "end_date"], name="contracts_c_status_537325_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["client", "status"], name="contracts_c_client__c0be66_idx"),
        ),
        migrations.AddConstraint(
            model_name="contractservice",
            constraint=models.UniqueConstraint(
                fields=("contract", "service"), name="unique_service_per_contract"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractversion",
            constraint=models.UniqueConstraint(
                fields=("contract", "version_number"), name="unique_contract_version_number"
            ),
        ),
    ]
